### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx-state-tree#31]
Just to write down what to do! :)

**Preparation**
- [x] Refactor and move factories

**Type System**
- [x] Basic type system #21 
- [x] Introduce Type #20 
- [x] Primitive type #24 
- [x] arrayOf(Type)
- [x] mapOf(Type)
- [x] withDefault #16 
- [x] Refinement types #43 
- [x] Specific primary types (string, number, boolean) #43 
- [x] Constant type (matches true when the value is exactly the same is: arg => value === arg) #36
- [x] maybe(Type) ( unionOf(null, Type) #36 
- [x] unionOf(Type, Type, ...Type) #17 
- [x] Frozen type (matches any serializable type. It's factory will be an identity function checking for serialization and then froze the argument)
- [ ] Array of References
- [ ] Map of References
- [X] References #55 

**Actions**
- [X] Serialize complex arguments as refs #55 
- [ ] Should actions allow to change only their node/child nodes? (redux does so, is really needed or it just enforces encapsulation?)

**Refactorings**
- [x] Move types to their own namespace #43 

**Testing**
- [ ] (almost) 100% code coverage

**Performance Optimizations**
- [ ] When applying a snapshot, find a more efficient way.
- [ ] 3-pass applySnapshot (get type tree, check snapshot, apply it)

**Docs**
- [ ] Rewrite examples
- [ ] Documentation
- [ ] Getting Started
- [ ] FAQ

**DevTools**
- [ ] Connect to redux-devtools

**Comment by hccampos** [comment]
Really impressive work so far, and great idea for state management. I am wondering, however, about why the choice was for factory functions versus supporting classes with decorators, like MobX. Maybe this is something that will come at a later stage?

**Comment by mattiamanzati** [comment]
The reason is pretty simple, constructor and private variables are difficult to serialize! Anyway will be probably a long term goal, not for the first versions! :)

**Comment by mweststrate** [comment]
I think this issue is double adminstration. Let's keep it to issues and milestones :)
